@startuml

!include commons.style
hide footbox
title Facade Pattern Behavior

participant "MedicalFileFacade" as F
participant "MedicalFile" as A

[-> F: updateMedicalVisit(medicalFile)
activate F
F -> A: setMedicalFile(medicalFile)
activate A
A --> F
deactivate A
[<-- F
deactivate F

@enduml
