@startuml

package "logic"{

' User is abstract class
  abstract class User {
    -id: String
    -userName: String
    -email: String
    -password: String
    -lastName: String
    -firstName: String
  }
together{
  class Patient extends User {
    -dateOfBirth: Date
    -gender: String
    -parents: String
    -cityOfBirth: String
    -healthInsuranceNumber: String
  }


  class Coordinates {
    -address: String
    -phones: List<String>
  }

  class MedicalFile {
    -healthInsuranceNumber: String
  }

  class MedicalHistory {
    -id: String
    -diagnostic: String
    -treatement: String
    -treatingDoctor: Doctor
    -beginningOfIllness: Date
    -endOfIllness: Date
  }

  class MedicalVisit {
    -id: String
    -establishement: String
    -doctor: Doctor
    -dateOfVisit: Date
    -diagnostic: String
    -treatement: String
    -summary: String
    -notes: List<String>
  }
}

together{
  class Doctor extends User {
  }

  class HealthCareProfessional extends User {
  }
}

  class Modification {
    -id: String
    -ModifiedMedicalFile: MedicalFile
    -date: Date
    -author: Doctor
    -ModifiedFields: Map<String, Pair<String, String>>
  }
}


Patient "1" *-- "1" Coordinates

MedicalFile "1" *-- "1" Patient
MedicalFile "1" *-- "0..*" MedicalVisit
MedicalFile "1" *-- "0..*" MedicalHistory

MedicalVisit "1" o-- "1" Doctor
MedicalHistory "1" o-- "1" Doctor
Modification "1" o-- "1" Doctor

MedicalFile "1" *-- "0..*" Modification


@enduml