@startuml

participant "Doctor" as Doctor
participant "System" as System
participant "Database" as Database

activate Doctor
Doctor -> System: modifyMedicalFile(file, Modifications)
activate System
System -> System: validateCredentials(credentials)
alt Doctor's credentials are valid
    System -> System: validateChanges(Modifications)
    alt Modifications are valid
        System -> Database: modifyMedicalFile(file, Modifications)
        activate Database
        Database --> Database: patchFile(file, Modifications)
        Database --> System: File
        System -> Database: archiveModification(file, Modifications)
        Database --> System: Modifications
        System --> Doctor: makeResponse(Modifications, "200 OK")
    else Modifications are not valid
        System --> Doctor: makeResponse("400 Bad Request")
    end
else Doctor's credentials are not valid
    System --> Doctor: makeResponse("403 Forbidden")
end
deactivate System

@enduml
