@startuml reconstructMedicalFileFromModification

participant "RAMQ" as RAMQ
participant "System" as System
participant "Database" as Database
participant "Archive" as Archive

RAMQ -> System: Send request to reconstruct Medical File from a certain modification
activate System
System -> Database: Retrieve current Medical File
activate Database
Database --> System: Return current Medical File
deactivate Database
System -> Archive: Retrieve certain modification
activate Archive
Archive --> System: Return certain modification
deactivate Archive
System -> System: Reconstruct Medical File from certain modification
System --> RAMQ: Send reconstructed Medical File

deactivate System

@enduml