@startuml

participant "Patient" as Patient
participant "System" as System
participant "Database" as Database

Patient -> System: modifyCoordinates()
activate System
System -> System: validatePatientCredentials(credentials)
alt Patient's credentials are valid
    System -> Coordinates: new(newCoordinates)
    Coordinates -> Coordinates: validateNewCoordites(newCoordinates)
    Coordinates -> System: NewCoordinatesValid
    alt newCoordinates are valid
        System -> Database: updateUserCoordinates(Coordinates)
        activate Database
        Database --> Database: patchUser(Coordinates)
        Database --> System: User
        deactivate Database
        System --> Patient: makeResponse(User, "200 OK")
    else New coordinates are not valid
        System --> Patient: makeResponse("400 Bad Request")
    end
else Patient's credentials are not valid
    System --> Patient: makeResponse("403 Forbidden")
end
deactivate System

@enduml
