@startuml 

participant "RAMQ" as RAMQ
participant "System" as System
participant "Database" as Database

RAMQ -> System: sendPatientInformation(patientInformation)
activate System
System -> System: validatePatientInformation(patientInformation)
alt Information is valid
    System -> Database: createMedicalFile(Information)
    Database -> Database: insertIntoTable(Information)
    Database -> System: File
    activate Database
    alt File Not Created
        System --> RAMQ: makeResponse("400 Bad Request")
    deactivate Database
    else File Created
        System --> RAMQ: makeResponse(File, "201")
    end
else Information is not valid
    System --> RAMQ: makeResponse("400 Bad Request")
end
deactivate System

@enduml
