@startuml

participant "RAMQ" as RAMQ
participant "System" as System
participant "Database" as Database

RAMQ -> System: getFileModifications(healthInsuranceNumber)
System -> System: validateFile(healthInsuranceNumber)
alt File is valid
    activate System
    System -> Database: getModifications(healthInsuranceNumber)
    activate Database
    Database --> System: Modifications
    deactivate Database
    System --> RAMQ: makeResponse(Modifications, "200 OK")
    else File is not valid
        System --> RAMQ: makeResponse("400 Bad Request")
    end

deactivate System

@enduml
