@startuml

participant "Doctor" as Doctor
participant "System" as System
participant "Database" as Database
participant "MedicalFile" as MedFile

activate Doctor
Doctor -> System: modifyMedicalFile(file, Modifications)
activate System
System -> System: validateCredentials(credentials)
alt Doctor's credentials are valid
    System -> Modification: new(Modifications)
    activate Modification
    Modification -> Modification: validateChanges()
    Modification -> System: AreModificationValid 
    alt Modifications are valid
        System -> MedFile: new(file)
        activate MedFile
        System -> Database: modifyMedicalFile(MedicalFile, Modification)
        activate Database
        Database --> Database: patchFile(MedicalFile, Modifications)
        Database --> System: MedicalFile
        System -> Database: archiveModification(MedicalFile, Modification)
        Database --> System: Modification
        deactivate Modification
        System --> Doctor: makeResponse(MedicalFile, "200 OK")
        deactivate MedFile
    else Modifications are not valid
        System --> Doctor: makeResponse("400 Bad Request")
    end
else Doctor's credentials are not valid
    System --> Doctor: makeResponse("403 Forbidden")
end
deactivate System

@enduml
