@startuml

participant "RAMQ" as RAMQ
participant "System" as System
participant "Database" as Database

activate RAMQ
RAMQ -> System: resetFileToDate(file, date)
activate System
System -> Database: getFile(file)
activate Database
Database -> System: File
System -> Database: getAllModificationsAfterDate(file, date)
Database --> System: Modifications
deactivate Archive
System -> System: reconstructAndSaveMedicalFileFromModifications(File, Modifications)
System -> RAMQ: MedicalFile
System --> RAMQ: makeResponse(MedicalFile, "200 OK")

deactivate System

@enduml

